spring:
    datasource:
            dataSourceClassName: org.h2.Driver
            url: jdbc:h2:file:./data/iop_db;
            databaseName: 
            serverName:
            username: 'sa'
            password: ''
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        database: H2
        openInView: false
        show_sql: true
        format_sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
     
    flyway:
        locations: classpath:db/migration
        table: flyway_schema_history
        enabled: true
management:
    server:
        port:9095
    endpoints:
        web:
            exposure:
                include: info,health,flyway        
                